sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t 5zinda/docker-react-app3 -f Dockerfile.dev .

script:
  - docker run -e CI=true 5zinda/docker-react-app3 npm run test -- --coverage

after_success:
  - echo "Test Success!"